name: find_go_app
description: Find Go App.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  sliding_up_panel: ^2.0.0+1

  #State Management
  get: ^4.6.1

  #Core Utility
  change_app_package_name: ^1.0.0
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.1.1
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/bottom_icons/
    - assets/bottom_sheet_icons/
    - assets/icon/
    - assets/profile_pictures/
    - assets/stars/
  
  #Aileron Font Family
  fonts:
    - family: Aileron-Bold     
      fonts:
        - asset: assets/fonts/ail/Aileron-Bold.otf
    - family: Aileron-Heavy     
      fonts:
        - asset: assets/fonts/ail/Aileron-Heavy.otf
    - family: Aileron-Light     
      fonts:
        - asset: assets/fonts/ail/Aileron-Light.otf  
    - family: Aileron-Regular     
      fonts:
        - asset: assets/fonts/ail/Aileron-Regular.otf
    - family: Aileron-SemiBold     
      fonts:
        - asset: assets/fonts/ail/Aileron-SemiBold.otf
    #MontSerrat Font Family
    - family: Montserrat-Regular     
      fonts:
        - asset: assets/fonts/mont/Montserrat-Regular.otf
    - family: Montserrat-SemiBold     
      fonts:
        - asset: assets/fonts/mont/Montserrat-SemiBold.otf

  


